[0.123s] Invoking command in '/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing': PYTEST_ADDOPTS=--tb=short --junit-xml=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml --junit-prefix=my_testing -o cache_dir=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache -s PYTHONDONTWRITEBYTECODE=1 /usr/bin/python3 -m pytest
[0.255s] [1m============================= test session starts ==============================[0m
[0.255s] platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
[0.257s] cachedir: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache
[0.257s] rootdir: /home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing
[0.257s] plugins: launch-testing-1.0.10, ament-lint-0.12.14, ament-copyright-0.12.14, ament-xmllint-0.12.14, launch-testing-ros-0.19.10, ament-pep257-0.12.14, ament-flake8-0.12.14, colcon-core-0.19.0, cov-3.0.0
[0.319s] [1mcollecting ... [0m[1m
[0.320s] collected 1 item                                                               [0m
[0.320s] 
[0.327s] test/test_integration.py [INFO] [launch]: All log files can be found below /home/phr/.ros/log/2025-08-05-22-52-36-691412-PHR-56078
[0.328s] [INFO] [launch]: Default logging verbosity is set to INFO
[0.337s] [INFO] [number_publisher-1]: process started with pid [56092]
[0.338s] [INFO] [number_processor-2]: process started with pid [56094]
[0.362s] test_communication_and_logic (test_integration.TestIntegration) ... [0m[INFO] [1754405556.733492474] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[0.435s] [number_processor-2] [INFO] [1754405556.805790813] [number_processor]: 数字处理节点已启动，等待接收数字...
[0.435s] [number_publisher-1] [INFO] [1754405556.805790813] [number_publisher]: 数字发布节点已启动，将从1开始发布...
[1.430s] [number_publisher-1] [INFO] [1754405557.801146784] [number_publisher]: 发布: 1
[1.430s] [number_processor-2] [INFO] [1754405557.801461424] [number_processor]: 收到: 1
[1.431s] [number_processor-2] [INFO] [1754405557.802204686] [number_processor]: 发布处理后结果: 3
[2.430s] [number_publisher-1] [INFO] [1754405558.801136870] [number_publisher]: 发布: 2
[2.430s] [number_processor-2] [INFO] [1754405558.801497816] [number_processor]: 收到: 2
[2.431s] [number_processor-2] [INFO] [1754405558.802161528] [number_processor]: 发布处理后结果: 6
[3.430s] [number_publisher-1] [INFO] [1754405559.801151893] [number_publisher]: 发布: 3
[3.431s] [number_processor-2] [INFO] [1754405559.801400043] [number_processor]: 收到: 3
[3.431s] [number_processor-2] [INFO] [1754405559.802117185] [number_processor]: 发布处理后结果: 9
[3.432s] [0m[INFO] [1754405559.803357935] [test_subscriber_node]: 检查接收到的消息。 Got: [3, 6, 9][0m
[3.438s] [0m[INFO] [1754405559.808182019] [test_subscriber_node]: 测试结束，销毁测试节点[0m
[3.439s] FAIL
[3.446s] test_processor_starts_ok (test_integration.TestIntegration) ... [0m[INFO] [1754405559.817745889] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[3.447s] [0m[INFO] [1754405559.818225566] [test_subscriber_node]: 正在检查 processor 节点的启动日志...[0m
[3.447s] [0m[INFO] [1754405559.818733739] [test_subscriber_node]: Processor 节点启动正常。[0m
[3.451s] [0m[INFO] [1754405559.822637650] [test_subscriber_node]: 测试结束，销毁测试节点[0m
[3.451s] ok
[3.459s] test_publisher_starts_ok (test_integration.TestIntegration) ... [0m[INFO] [1754405559.830134394] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[3.459s] [0m[INFO] [1754405559.830604573] [test_subscriber_node]: 正在检查 publisher 节点的启动日志...[0m
[3.460s] [0m[INFO] [1754405559.831086625] [test_subscriber_node]: Publisher 节点启动正常。[0m
[3.464s] [0m[INFO] [1754405559.835091458] [test_subscriber_node]: 测试结束，销毁测试节点[0m
[3.464s] ok
[3.464s] 
[3.464s] ======================================================================
[3.464s] FAIL: test_communication_and_logic (test_integration.TestIntegration)
[3.464s] ----------------------------------------------------------------------
[3.464s] Traceback (most recent call last):
[3.465s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 84, in test_communication_and_logic
[3.465s]     self.assertEqual(sorted(self.received_messages), sorted(expected_results))
[3.465s] AssertionError: Lists differ: [3, 6, 9] != [2, 4, 6]
[3.465s] 
[3.465s] First differing element 0:
[3.465s] 3
[3.465s] 2
[3.465s] 
[3.465s] - [3, 6, 9]
[3.465s] + [2, 4, 6]
[3.465s] 
[3.465s] ----------------------------------------------------------------------
[3.465s] Ran 3 tests in 3.136s
[3.466s] 
[3.466s] FAILED (failures=1)
[3.466s] [INFO] [number_processor-2]: sending signal 'SIGINT' to process[number_processor-2]
[3.466s] [INFO] [number_publisher-1]: sending signal 'SIGINT' to process[number_publisher-1]
[3.467s] [number_processor-2] Traceback (most recent call last):
[3.467s] [number_processor-2]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor", line 33, in <module>
[3.467s] [number_processor-2]     sys.exit(load_entry_point('my-algorithms==0.0.0', 'console_scripts', 'number_processor')())
[3.468s] [number_processor-2]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/python3.10/site-packages/my_algorithms/number_processor_node.py", line 32, in main
[3.468s] [number_processor-2]     rclpy.spin(node)
[3.468s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 229, in spin
[3.468s] [number_processor-2]     executor.spin_once()
[3.468s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
[3.468s] [number_processor-2]     self._spin_once_impl(timeout_sec)
[3.468s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
[3.468s] [number_publisher-1] Traceback (most recent call last):
[3.469s] [number_publisher-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_publisher", line 33, in <module>
[3.469s] [number_publisher-1]     sys.exit(load_entry_point('my-algorithms==0.0.0', 'console_scripts', 'number_publisher')())
[3.469s] [number_publisher-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/python3.10/site-packages/my_algorithms/number_publisher_node.py", line 25, in main
[3.469s] [number_publisher-1]     rclpy.spin(node)
[3.469s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 229, in spin
[3.469s] [number_publisher-1]     executor.spin_once()
[3.469s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
[3.469s] [number_processor-2]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[3.469s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[3.469s] [number_processor-2]     return next(self._cb_iter)
[3.469s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
[3.470s] [number_processor-2]     wait_set.wait(timeout_nsec)
[3.470s] [number_processor-2] KeyboardInterrupt
[3.470s] [number_publisher-1]     self._spin_once_impl(timeout_sec)
[3.470s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
[3.470s] [number_publisher-1]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[3.470s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[3.470s] [number_publisher-1]     return next(self._cb_iter)
[3.470s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
[3.470s] [number_publisher-1]     wait_set.wait(timeout_nsec)
[3.470s] [number_publisher-1] KeyboardInterrupt
[3.494s] [ERROR] [number_publisher-1]: process has died [pid 56092, exit code -2, cmd '/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_publisher --ros-args -r __node:=number_publisher'].
[3.495s] [ERROR] [number_processor-2]: process has died [pid 56094, exit code -2, cmd '/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor --ros-args -r __node:=number_processor'].
[3.495s] 
[3.495s] ----------------------------------------------------------------------
[3.495s] Ran 0 tests in 0.000s
[3.495s] 
[3.496s] OK
[3.504s] [31mF[0m
[3.504s] 
[3.505s] =================================== FAILURES ===================================
[3.505s] [31m[1m________________________ launch tests: test_integration ________________________[0m
[3.505s] 
[3.505s] ==========================================================================================================================================
[3.505s] FAIL: test_integration.TestIntegration.test_communication_and_logic
[3.505s] ------------------------------------------------------------------------------------------------------------------------------------------
[3.505s] Traceback (most recent call last):
[3.505s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 84, in test_communication_and_logic
[3.505s]     self.assertEqual(sorted(self.received_messages), sorted(expected_results))
[3.506s] AssertionError: Lists differ: [3, 6, 9] != [2, 4, 6]
[3.506s] 
[3.506s] First differing element 0:
[3.506s] 3
[3.506s] 2
[3.506s] 
[3.506s] - [3, 6, 9]
[3.506s] + [2, 4, 6]
[3.506s] - generated xml file: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml -
[3.506s] =========================== short test summary info ============================
[3.507s] FAILED test/test_integration.py::test_integration - test_integration.TestInte...
[3.507s] [31m============================== [31m[1m1 failed[0m[31m in 3.25s[0m[31m ===============================[0m
[3.669s] Invoked command in '/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing' returned '1': PYTEST_ADDOPTS=--tb=short --junit-xml=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml --junit-prefix=my_testing -o cache_dir=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache -s PYTHONDONTWRITEBYTECODE=1 /usr/bin/python3 -m pytest
