[0.121s] Invoking command in '/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing': PYTEST_ADDOPTS=--tb=short --junit-xml=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml --junit-prefix=my_testing -o cache_dir=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache -s PYTHONDONTWRITEBYTECODE=1 /usr/bin/python3 -m pytest
[0.255s] [1m============================= test session starts ==============================[0m
[0.255s] platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
[0.257s] cachedir: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache
[0.257s] rootdir: /home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing
[0.257s] plugins: launch-testing-1.0.10, ament-lint-0.12.14, ament-copyright-0.12.14, ament-xmllint-0.12.14, launch-testing-ros-0.19.10, ament-pep257-0.12.14, ament-flake8-0.12.14, colcon-core-0.19.0, cov-3.0.0
[0.319s] [1mcollecting ... [0m[1m
[0.319s] collected 1 item                                                               [0m
[0.319s] 
[0.327s] test/test_integration.py [INFO] [launch]: All log files can be found below /home/phr/.ros/log/2025-08-05-22-53-56-296130-PHR-56599
[0.327s] [INFO] [launch]: Default logging verbosity is set to INFO
[0.337s] [INFO] [number_publisher-1]: process started with pid [56613]
[0.337s] [INFO] [number_processor-2]: process started with pid [56615]
[0.361s] test_communication_and_logic (test_integration.TestIntegration) ... [0m[INFO] [1754405636.337490768] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[0.433s] [number_processor-2] [INFO] [1754405636.409201020] [number_processor]: 数字处理节点已启动，等待接收数字...
[0.433s] [number_publisher-1] [INFO] [1754405636.409203394] [number_publisher]: 数字发布节点已启动，将从1开始发布...
[1.429s] [number_publisher-1] [INFO] [1754405637.404553300] [number_publisher]: 发布: 1
[1.429s] [number_processor-2] [INFO] [1754405637.405152884] [number_processor]: 收到: 1
[1.430s] [number_processor-2] [INFO] [1754405637.405891381] [number_processor]: 发布处理后结果: 3
[2.429s] [number_publisher-1] [INFO] [1754405638.404530134] [number_publisher]: 发布: 2
[2.429s] [number_processor-2] [INFO] [1754405638.404916005] [number_processor]: 收到: 2
[2.430s] [number_processor-2] [INFO] [1754405638.405620071] [number_processor]: 发布处理后结果: 6
[3.429s] [number_publisher-1] [INFO] [1754405639.404534316] [number_publisher]: 发布: 3
[3.429s] [number_processor-2] [INFO] [1754405639.404951056] [number_processor]: 收到: 3
[3.430s] [number_processor-2] [INFO] [1754405639.405741795] [number_processor]: 发布处理后结果: 9
[3.430s] [0m[INFO] [1754405639.406874475] [test_subscriber_node]: 检查接收到的消息。 Got: [3, 6, 9][0m
[3.435s] [0m[INFO] [1754405639.411517987] [test_subscriber_node]: 测试结束，销毁测试节点[0m
[3.435s] FAIL
[3.443s] test_processor_starts_ok (test_integration.TestIntegration) ... [0m[INFO] [1754405639.419506109] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[3.444s] [0m[INFO] [1754405639.420007148] [test_subscriber_node]: 正在检查 processor 节点的启动日志...[0m
[3.444s] [0m[INFO] [1754405639.420527183] [test_subscriber_node]: Processor 节点启动正常。[0m
[3.447s] [0m[INFO] [1754405639.423861108] [test_subscriber_node]: 测试结束，销毁测试节点[0m
[3.448s] ok
[3.456s] test_publisher_starts_ok (test_integration.TestIntegration) ... [0m[INFO] [1754405639.431971523] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[3.456s] [0m[INFO] [1754405639.432550923] [test_subscriber_node]: 正在检查 publisher 节点的启动日志...[0m
[3.457s] [0m[INFO] [1754405639.433119637] [test_subscriber_node]: Publisher 节点启动正常。[0m
[3.460s] [0m[INFO] [1754405639.436565168] [test_subscriber_node]: 测试结束，销毁测试节点[0m
[3.460s] ok
[3.461s] 
[3.461s] ======================================================================
[3.461s] FAIL: test_communication_and_logic (test_integration.TestIntegration)
[3.461s] ----------------------------------------------------------------------
[3.461s] Traceback (most recent call last):
[3.461s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 84, in test_communication_and_logic
[3.461s]     self.assertEqual(sorted(self.received_messages), sorted(expected_results))
[3.461s] AssertionError: Lists differ: [3, 6, 9] != [2, 4, 6]
[3.461s] 
[3.461s] First differing element 0:
[3.462s] 3
[3.462s] 2
[3.462s] 
[3.462s] - [3, 6, 9]
[3.462s] + [2, 4, 6]
[3.462s] 
[3.462s] ----------------------------------------------------------------------
[3.462s] Ran 3 tests in 3.132s
[3.462s] 
[3.463s] FAILED (failures=1)
[3.463s] [INFO] [number_processor-2]: sending signal 'SIGINT' to process[number_processor-2]
[3.463s] [INFO] [number_publisher-1]: sending signal 'SIGINT' to process[number_publisher-1]
[3.464s] [number_processor-2] Traceback (most recent call last):
[3.464s] [number_processor-2]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor", line 33, in <module>
[3.464s] [number_processor-2]     sys.exit(load_entry_point('my-algorithms==0.0.0', 'console_scripts', 'number_processor')())
[3.464s] [number_processor-2]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/python3.10/site-packages/my_algorithms/number_processor_node.py", line 32, in main
[3.464s] [number_processor-2]     rclpy.spin(node)
[3.465s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 229, in spin
[3.465s] [number_processor-2]     executor.spin_once()
[3.465s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
[3.465s] [number_processor-2]     self._spin_once_impl(timeout_sec)
[3.465s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
[3.466s] [number_processor-2]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[3.466s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[3.466s] [number_processor-2]     return next(self._cb_iter)
[3.466s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
[3.466s] [number_processor-2]     wait_set.wait(timeout_nsec)
[3.466s] [number_processor-2] KeyboardInterrupt
[3.466s] [number_publisher-1] Traceback (most recent call last):
[3.466s] [number_publisher-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_publisher", line 33, in <module>
[3.467s] [number_publisher-1]     sys.exit(load_entry_point('my-algorithms==0.0.0', 'console_scripts', 'number_publisher')())
[3.467s] [number_publisher-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/python3.10/site-packages/my_algorithms/number_publisher_node.py", line 25, in main
[3.467s] [number_publisher-1]     rclpy.spin(node)
[3.467s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 229, in spin
[3.467s] [number_publisher-1]     executor.spin_once()
[3.467s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
[3.467s] [number_publisher-1]     self._spin_once_impl(timeout_sec)
[3.467s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
[3.467s] [number_publisher-1]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[3.467s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[3.467s] [number_publisher-1]     return next(self._cb_iter)
[3.468s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
[3.468s] [number_publisher-1]     wait_set.wait(timeout_nsec)
[3.468s] [number_publisher-1] KeyboardInterrupt
[3.491s] [ERROR] [number_publisher-1]: process has died [pid 56613, exit code -2, cmd '/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_publisher --ros-args -r __node:=number_publisher'].
[3.491s] [ERROR] [number_processor-2]: process has died [pid 56615, exit code -2, cmd '/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor --ros-args -r __node:=number_processor'].
[3.492s] 
[3.492s] ----------------------------------------------------------------------
[3.492s] Ran 0 tests in 0.000s
[3.492s] 
[3.492s] OK
[3.501s] [31mF[0m
[3.501s] 
[3.501s] =================================== FAILURES ===================================
[3.501s] [31m[1m________________________ launch tests: test_integration ________________________[0m
[3.501s] 
[3.501s] ==========================================================================================================================================
[3.501s] FAIL: test_integration.TestIntegration.test_communication_and_logic
[3.501s] ------------------------------------------------------------------------------------------------------------------------------------------
[3.501s] Traceback (most recent call last):
[3.502s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 84, in test_communication_and_logic
[3.502s]     self.assertEqual(sorted(self.received_messages), sorted(expected_results))
[3.502s] AssertionError: Lists differ: [3, 6, 9] != [2, 4, 6]
[3.502s] 
[3.502s] First differing element 0:
[3.502s] 3
[3.502s] 2
[3.502s] 
[3.502s] - [3, 6, 9]
[3.502s] + [2, 4, 6]
[3.503s] - generated xml file: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml -
[3.503s] =========================== short test summary info ============================
[3.503s] FAILED test/test_integration.py::test_integration - test_integration.TestInte...
[3.503s] [31m============================== [31m[1m1 failed[0m[31m in 3.25s[0m[31m ===============================[0m
[3.674s] Invoked command in '/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing' returned '1': PYTEST_ADDOPTS=--tb=short --junit-xml=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml --junit-prefix=my_testing -o cache_dir=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache -s PYTHONDONTWRITEBYTECODE=1 /usr/bin/python3 -m pytest
