[0.150s] Invoking command in '/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing': PYTEST_ADDOPTS=--tb=short --junit-xml=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml --junit-prefix=my_testing -o cache_dir=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache -s PYTHONDONTWRITEBYTECODE=1 /usr/bin/python3 -m pytest
[0.294s] [1m============================= test session starts ==============================[0m
[0.294s] platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
[0.296s] cachedir: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache
[0.296s] rootdir: /home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing
[0.296s] plugins: launch-testing-1.0.10, ament-lint-0.12.14, ament-copyright-0.12.14, ament-xmllint-0.12.14, launch-testing-ros-0.19.10, ament-pep257-0.12.14, ament-flake8-0.12.14, colcon-core-0.19.0, cov-3.0.0
[0.359s] [1mcollecting ... [0m[1m
[0.359s] collected 1 item                                                               [0m
[0.359s] 
[0.367s] test/test_integration.py [INFO] [launch]: All log files can be found below /home/phr/.ros/log/2025-08-05-22-38-49-538904-PHR-53256
[0.367s] [INFO] [launch]: Default logging verbosity is set to INFO
[0.382s] [INFO] [number_publisher-1]: process started with pid [53270]
[0.382s] [INFO] [number_processor-2]: process started with pid [53272]
[0.405s] test_communication_and_logic (test_integration.TestIntegration) ... [0m[INFO] [1754404729.584371771] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[0.477s] [number_processor-2] [INFO] [1754404729.655906287] [number_processor]: 数字处理节点已启动，等待接收数字...
[0.477s] [number_publisher-1] [INFO] [1754404729.655931221] [number_publisher]: 数字发布节点已启动，将从1开始发布...
[1.472s] [number_publisher-1] [INFO] [1754404730.650856922] [number_publisher]: 发布: 1
[1.472s] [number_processor-2] [INFO] [1754404730.651139502] [number_processor]: 收到: 1
[1.473s] [number_processor-2] [INFO] [1754404730.651552688] [number_processor]: 发布处理后结果: 3
[2.472s] [number_publisher-1] [INFO] [1754404731.651148110] [number_publisher]: 发布: 2
[2.473s] [number_processor-2] [INFO] [1754404731.651366575] [number_processor]: 收到: 2
[2.473s] [number_processor-2] [INFO] [1754404731.651966169] [number_processor]: 发布处理后结果: 6
[3.472s] [number_publisher-1] [INFO] [1754404732.651166228] [number_publisher]: 发布: 3
[3.473s] [number_processor-2] [INFO] [1754404732.651358573] [number_processor]: 收到: 3
[3.473s] [number_processor-2] [INFO] [1754404732.652029406] [number_processor]: 发布处理后结果: 9
[3.474s] [0m[INFO] [1754404732.653302207] [test_subscriber_node]: 检查接收到的消息。 Got: [3, 6, 9][0m
[3.478s] [0m[INFO] [1754404732.657587226] [test_subscriber_node]: 测试结束，销毁测试节点[0m
[3.478s] FAIL
[3.487s] test_processor_starts_ok (test_integration.TestIntegration) ... [0m[INFO] [1754404732.666634563] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[3.488s] [0m[INFO] [1754404732.667305396] [test_subscriber_node]: 正在检查 processor 节点的启动日志...[0m
[4.472s] [number_publisher-1] [INFO] [1754404733.651049005] [number_publisher]: 发布: 4
[4.472s] [number_processor-2] [INFO] [1754404733.651412324] [number_processor]: 收到: 4
[4.473s] [number_processor-2] [INFO] [1754404733.651976298] [number_processor]: 发布处理后结果: 12
[5.472s] [number_publisher-1] [INFO] [1754404734.651049339] [number_publisher]: 发布: 5
[5.473s] [number_processor-2] [INFO] [1754404734.651375851] [number_processor]: 收到: 5
[5.473s] [number_processor-2] [INFO] [1754404734.651926765] [number_processor]: 发布处理后结果: 15
[6.472s] [number_publisher-1] [INFO] [1754404735.651087680] [number_publisher]: 发布: 6
[6.472s] [number_processor-2] [INFO] [1754404735.651422503] [number_processor]: 收到: 6
[6.473s] [number_processor-2] [INFO] [1754404735.652028033] [number_processor]: 发布处理后结果: 18
[7.472s] [number_publisher-1] [INFO] [1754404736.651143843] [number_publisher]: 发布: 7
[7.472s] [number_processor-2] [INFO] [1754404736.651377744] [number_processor]: 收到: 7
[7.473s] [number_processor-2] [INFO] [1754404736.651909661] [number_processor]: 发布处理后结果: 21
[8.472s] [number_publisher-1] [INFO] [1754404737.651107408] [number_publisher]: 发布: 8
[8.473s] [number_processor-2] [INFO] [1754404737.651393551] [number_processor]: 收到: 8
[8.473s] [number_processor-2] [INFO] [1754404737.651961088] [number_processor]: 发布处理后结果: 24
[9.472s] [number_publisher-1] [INFO] [1754404738.651048427] [number_publisher]: 发布: 9
[9.472s] [number_processor-2] [INFO] [1754404738.651331008] [number_processor]: 收到: 9
[9.473s] [number_processor-2] [INFO] [1754404738.651884297] [number_processor]: 发布处理后结果: 27
[10.472s] [number_publisher-1] [INFO] [1754404739.651124813] [number_publisher]: 发布: 10
[10.472s] [number_processor-2] [INFO] [1754404739.651345653] [number_processor]: 收到: 10
[10.473s] [number_processor-2] [INFO] [1754404739.651897754] [number_processor]: 发布处理后结果: 30
[11.472s] [number_publisher-1] [INFO] [1754404740.651086041] [number_publisher]: 发布: 11
[11.472s] [number_processor-2] [INFO] [1754404740.651488541] [number_processor]: 收到: 11
[11.473s] [number_processor-2] [INFO] [1754404740.652104757] [number_processor]: 发布处理后结果: 33
[12.472s] [number_publisher-1] [INFO] [1754404741.651072215] [number_publisher]: 发布: 12
[12.472s] [number_processor-2] [INFO] [1754404741.651504398] [number_processor]: 收到: 12
[12.473s] [number_processor-2] [INFO] [1754404741.652141986] [number_processor]: 发布处理后结果: 36
[13.472s] [number_publisher-1] [INFO] [1754404742.651041780] [number_publisher]: 发布: 13
[13.472s] [number_processor-2] [INFO] [1754404742.651300614] [number_processor]: 收到: 13
[13.473s] [number_processor-2] [INFO] [1754404742.651821845] [number_processor]: 发布处理后结果: 39
[13.493s] [0m[INFO] [1754404742.671914774] [test_subscriber_node]: 测试结束，销毁测试节点[0m
[13.493s] FAIL
[13.501s] test_publisher_starts_ok (test_integration.TestIntegration) ... [0m[INFO] [1754404742.680476500] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[13.501s] [0m[INFO] [1754404742.680964487] [test_subscriber_node]: 正在检查 publisher 节点的启动日志...[0m
[14.165s] [WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[14.166s] [number_processor-2] Traceback (most recent call last):
[14.166s] [number_processor-2]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor", line 33, in <module>
[14.166s] [number_processor-2]     sys.exit(load_entry_point('my-algorithms==0.0.0', 'console_scripts', 'number_processor')())
[14.166s] [number_processor-2]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/python3.10/site-packages/my_algorithms/number_processor_node.py", line 32, in main
[14.167s] [number_processor-2]     rclpy.spin(node)
[14.167s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 229, in spin
[14.167s] [number_processor-2]     executor.spin_once()
[14.167s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
[14.167s] [number_processor-2]     self._spin_once_impl(timeout_sec)
[14.167s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
[14.167s] [number_processor-2]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[14.167s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[14.168s] [number_processor-2]     return next(self._cb_iter)
[14.168s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
[14.168s] [number_processor-2]     wait_set.wait(timeout_nsec)
[14.168s] [number_processor-2] KeyboardInterrupt
[14.168s] [number_publisher-1] Traceback (most recent call last):
[14.168s] [number_publisher-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_publisher", line 33, in <module>
[14.168s] [number_publisher-1]     sys.exit(load_entry_point('my-algorithms==0.0.0', 'console_scripts', 'number_publisher')())
[14.168s] [number_publisher-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/python3.10/site-packages/my_algorithms/number_publisher_node.py", line 25, in main
[14.169s] [number_publisher-1]     rclpy.spin(node)
[14.169s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 229, in spin
[14.169s] [number_publisher-1]     executor.spin_once()
[14.169s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
[14.169s] [number_publisher-1]     self._spin_once_impl(timeout_sec)
[14.169s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
[14.169s] [number_publisher-1]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[14.169s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[14.169s] [number_publisher-1]     return next(self._cb_iter)
[14.169s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
[14.169s] [number_publisher-1]     wait_set.wait(timeout_nsec)
[14.169s] [number_publisher-1] KeyboardInterrupt
[14.194s] [ERROR] [number_publisher-1]: process has died [pid 53270, exit code -2, cmd '/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_publisher --ros-args -r __node:=number_publisher'].
[14.196s] [ERROR] [number_processor-2]: process has died [pid 53272, exit code -2, cmd '/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor --ros-args -r __node:=number_processor'].
[14.196s] Processes under test stopped before tests completed
[14.196s] Process 'number_publisher-1' exited with -2
[14.196s] ##### 'number_publisher-1' output #####
[14.255s] [31mF[0m
[14.255s] 
[14.255s] =================================== FAILURES ===================================
[14.255s] [31m[1m________________________ launch tests: test_integration ________________________[0m
[14.256s] [1m[31m/usr/lib/python3/dist-packages/_pytest/runner.py[0m:311: in from_call
[14.302s]     result: Optional[TResult] = func()
[14.303s] [1m[31m/usr/lib/python3/dist-packages/_pytest/runner.py[0m:255: in <lambda>
[14.303s]     [94mlambda[39;49;00m: ihook(item=item, **kwds), when=when, reraise=reraise
[14.303s] [1m[31m/usr/lib/python3/dist-packages/pluggy/hooks.py[0m:286: in __call__
[14.303s]     [94mreturn[39;49;00m [96mself[39;49;00m._hookexec([96mself[39;49;00m, [96mself[39;49;00m.get_hookimpls(), kwargs)
[14.303s] [1m[31m/usr/lib/python3/dist-packages/pluggy/manager.py[0m:92: in _hookexec
[14.303s]     [94mreturn[39;49;00m [96mself[39;49;00m._inner_hookexec(hook, methods, kwargs)
[14.303s] [1m[31m/usr/lib/python3/dist-packages/pluggy/manager.py[0m:83: in <lambda>
[14.304s]     [96mself[39;49;00m._inner_hookexec = [94mlambda[39;49;00m hook, methods, kwargs: hook.multicall(
[14.304s] [1m[31m/usr/lib/python3/dist-packages/pluggy/callers.py[0m:208: in _multicall
[14.304s]     [94mreturn[39;49;00m outcome.get_result()
[14.304s] [1m[31m/usr/lib/python3/dist-packages/pluggy/callers.py[0m:80: in get_result
[14.304s]     [94mraise[39;49;00m ex[[94m1[39;49;00m].with_traceback(ex[[94m2[39;49;00m])
[14.304s] [1m[31m/usr/lib/python3/dist-packages/pluggy/callers.py[0m:187: in _multicall
[14.304s]     res = hook_impl.function(*args)
[14.304s] [1m[31m/usr/lib/python3/dist-packages/_pytest/runner.py[0m:170: in pytest_runtest_call
[14.304s]     [94mraise[39;49;00m e
[14.305s] [1m[31m/usr/lib/python3/dist-packages/_pytest/runner.py[0m:162: in pytest_runtest_call
[14.305s]     item.runtest()
[14.305s] [1m[31m/opt/ros/humble/lib/python3.10/site-packages/launch_testing/pytest/hooks.py[0m:112: in runtest
[14.305s]     results_per_run = runner.run()
[14.305s] [1m[31m/opt/ros/humble/lib/python3.10/site-packages/launch_testing/test_runner.py[0m:256: in run
[14.305s]     results[run] = worker.run()
[14.305s] [1m[31m/opt/ros/humble/lib/python3.10/site-packages/launch_testing/test_runner.py[0m:167: in run
[14.305s]     [96mself[39;49;00m._print_process_output_summary(proc_info, proc_output)
[14.305s] [1m[31m/opt/ros/humble/lib/python3.10/site-packages/launch_testing/test_runner.py[0m:209: in _print_process_output_summary
[14.305s]     [96mprint[39;49;00m([33m'[39;49;00m[33m{}[39;49;00m[33m'[39;49;00m.format(io.text.decode([33m'[39;49;00m[33mascii[39;49;00m[33m'[39;49;00m)))
[14.305s] [1m[31mE   UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 50: ordinal not in range(128)[0m
[14.305s] - generated xml file: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml -
[14.306s] =========================== short test summary info ============================
[14.306s] FAILED test/test_integration.py::test_integration - UnicodeDecodeError: 'asci...
[14.306s] [31m============================== [31m[1m1 failed[0m[31m in 14.01s[0m[31m ==============================[0m
[14.472s] Invoked command in '/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing' returned '1': PYTEST_ADDOPTS=--tb=short --junit-xml=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml --junit-prefix=my_testing -o cache_dir=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache -s PYTHONDONTWRITEBYTECODE=1 /usr/bin/python3 -m pytest
