[0.124s] Invoking command in '/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing': PYTEST_ADDOPTS=--tb=short --junit-xml=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml --junit-prefix=my_testing -o cache_dir=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache PYTHONDONTWRITEBYTECODE=1 /usr/bin/python3 -m pytest
[0.258s] [1m============================= test session starts ==============================[0m
[0.258s] platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
[0.260s] cachedir: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache
[0.260s] rootdir: /home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing
[0.260s] plugins: launch-testing-1.0.10, ament-lint-0.12.14, ament-copyright-0.12.14, ament-xmllint-0.12.14, launch-testing-ros-0.19.10, ament-pep257-0.12.14, ament-flake8-0.12.14, colcon-core-0.19.0, cov-3.0.0
[0.322s] [1mcollecting ... [0m[1m
[0.322s] collected 1 item                                                               [0m
[0.322s] 
[3.500s] test/test_integration.py [31mF[0m[31m                                               [100%][0m
[3.500s] 
[3.500s] =================================== FAILURES ===================================
[3.500s] [31m[1m________________________ launch tests: test_integration ________________________[0m
[3.500s] 
[3.500s] ==========================================================================================================================================
[3.500s] FAIL: test_integration.TestIntegration.test_communication_and_logic
[3.500s] ------------------------------------------------------------------------------------------------------------------------------------------
[3.500s] Traceback (most recent call last):
[3.501s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 84, in test_communication_and_logic
[3.501s]     self.assertEqual(sorted(self.received_messages), sorted(expected_results))
[3.501s] AssertionError: Lists differ: [3, 6, 9] != [2, 4, 6]
[3.501s] 
[3.501s] First differing element 0:
[3.501s] 3
[3.501s] 2
[3.501s] 
[3.501s] - [3, 6, 9]
[3.501s] + [2, 4, 6]
[3.501s] ----------------------------- Captured stdout call -----------------------------
[3.501s] [INFO] [launch]: All log files can be found below /home/phr/.ros/log/2025-08-05-22-47-49-668882-PHR-55566
[3.501s] [INFO] [launch]: Default logging verbosity is set to INFO
[3.502s] [INFO] [number_publisher-1]: process started with pid [55580]
[3.502s] [INFO] [number_processor-2]: process started with pid [55582]
[3.502s] [number_publisher-1] [INFO] [1754405269.782316646] [number_publisher]: 数字发布节点已启动，将从1开始发布...
[3.502s] [number_processor-2] [INFO] [1754405269.782491182] [number_processor]: 数字处理节点已启动，等待接收数字...
[3.502s] [number_publisher-1] [INFO] [1754405270.777442493] [number_publisher]: 发布: 1
[3.502s] [number_processor-2] [INFO] [1754405270.777772568] [number_processor]: 收到: 1
[3.502s] [number_processor-2] [INFO] [1754405270.778324672] [number_processor]: 发布处理后结果: 3
[3.502s] [number_publisher-1] [INFO] [1754405271.777382926] [number_publisher]: 发布: 2
[3.502s] [number_processor-2] [INFO] [1754405271.777623952] [number_processor]: 收到: 2
[3.502s] [number_processor-2] [INFO] [1754405271.778203364] [number_processor]: 发布处理后结果: 6
[3.502s] [number_publisher-1] [INFO] [1754405272.777411224] [number_publisher]: 发布: 3
[3.502s] [number_processor-2] [INFO] [1754405272.777689057] [number_processor]: 收到: 3
[3.502s] [number_processor-2] [INFO] [1754405272.778277968] [number_processor]: 发布处理后结果: 9
[3.502s] [INFO] [number_processor-2]: sending signal 'SIGINT' to process[number_processor-2]
[3.503s] [INFO] [number_publisher-1]: sending signal 'SIGINT' to process[number_publisher-1]
[3.503s] [number_processor-2] Traceback (most recent call last):
[3.503s] [number_processor-2]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor", line 33, in <module>
[3.503s] [number_processor-2]     sys.exit(load_entry_point('my-algorithms==0.0.0', 'console_scripts', 'number_processor')())
[3.503s] [number_processor-2]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/python3.10/site-packages/my_algorithms/number_processor_node.py", line 32, in main
[3.503s] [number_processor-2]     rclpy.spin(node)
[3.503s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 229, in spin
[3.503s] [number_processor-2]     executor.spin_once()
[3.503s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
[3.503s] [number_processor-2]     self._spin_once_impl(timeout_sec)
[3.503s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
[3.503s] [number_processor-2]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[3.504s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[3.504s] [number_processor-2]     return next(self._cb_iter)
[3.504s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
[3.504s] [number_processor-2]     wait_set.wait(timeout_nsec)
[3.504s] [number_processor-2] KeyboardInterrupt
[3.504s] [number_publisher-1] Traceback (most recent call last):
[3.504s] [number_publisher-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_publisher", line 33, in <module>
[3.504s] [number_publisher-1]     sys.exit(load_entry_point('my-algorithms==0.0.0', 'console_scripts', 'number_publisher')())
[3.504s] [number_publisher-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/python3.10/site-packages/my_algorithms/number_publisher_node.py", line 25, in main
[3.504s] [number_publisher-1]     rclpy.spin(node)
[3.504s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 229, in spin
[3.504s] [number_publisher-1]     executor.spin_once()
[3.505s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
[3.505s] [number_publisher-1]     self._spin_once_impl(timeout_sec)
[3.505s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
[3.505s] [number_publisher-1]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[3.505s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[3.505s] [number_publisher-1]     return next(self._cb_iter)
[3.505s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
[3.505s] [number_publisher-1]     wait_set.wait(timeout_nsec)
[3.505s] [number_publisher-1] KeyboardInterrupt
[3.505s] [ERROR] [number_processor-2]: process has died [pid 55582, exit code -2, cmd '/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor --ros-args -r __node:=number_processor'].
[3.505s] [ERROR] [number_publisher-1]: process has died [pid 55580, exit code -2, cmd '/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_publisher --ros-args -r __node:=number_publisher'].
[3.505s] ----------------------------- Captured stderr call -----------------------------
[3.506s] test_communication_and_logic (test_integration.TestIntegration) ... [INFO] [1754405269.709917456] [test_subscriber_node]: 测试节点test_subscriber_node已创建
[3.506s] [INFO] [1754405272.779301437] [test_subscriber_node]: 检查接收到的消息。 Got: [3, 6, 9]
[3.506s] [INFO] [1754405272.783759822] [test_subscriber_node]: 测试结束，销毁测试节点
[3.506s] FAIL
[3.506s] test_processor_starts_ok (test_integration.TestIntegration) ... [INFO] [1754405272.792039002] [test_subscriber_node]: 测试节点test_subscriber_node已创建
[3.506s] [INFO] [1754405272.792518680] [test_subscriber_node]: 正在检查 processor 节点的启动日志...
[3.506s] [INFO] [1754405272.793007855] [test_subscriber_node]: Processor 节点启动正常。
[3.506s] [INFO] [1754405272.796229054] [test_subscriber_node]: 测试结束，销毁测试节点
[3.506s] ok
[3.506s] test_publisher_starts_ok (test_integration.TestIntegration) ... [INFO] [1754405272.803210493] [test_subscriber_node]: 测试节点test_subscriber_node已创建
[3.506s] [INFO] [1754405272.803687796] [test_subscriber_node]: 正在检查 publisher 节点的启动日志...
[3.507s] [INFO] [1754405272.804153225] [test_subscriber_node]: Publisher 节点启动正常。
[3.507s] [INFO] [1754405272.807331680] [test_subscriber_node]: 测试结束，销毁测试节点
[3.507s] ok
[3.507s] 
[3.507s] ======================================================================
[3.507s] FAIL: test_communication_and_logic (test_integration.TestIntegration)
[3.507s] ----------------------------------------------------------------------
[3.507s] Traceback (most recent call last):
[3.507s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 84, in test_communication_and_logic
[3.507s]     self.assertEqual(sorted(self.received_messages), sorted(expected_results))
[3.507s] AssertionError: Lists differ: [3, 6, 9] != [2, 4, 6]
[3.507s] 
[3.507s] First differing element 0:
[3.508s] 3
[3.508s] 2
[3.508s] 
[3.508s] - [3, 6, 9]
[3.508s] + [2, 4, 6]
[3.508s] 
[3.508s] ----------------------------------------------------------------------
[3.508s] Ran 3 tests in 3.130s
[3.508s] 
[3.508s] FAILED (failures=1)
[3.508s] 
[3.508s] ----------------------------------------------------------------------
[3.508s] Ran 0 tests in 0.000s
[3.508s] 
[3.508s] OK
[3.509s] - generated xml file: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml -
[3.509s] =========================== short test summary info ============================
[3.509s] FAILED test/test_integration.py::test_integration - test_integration.TestInte...
[3.509s] [31m============================== [31m[1m1 failed[0m[31m in 3.24s[0m[31m ===============================[0m
[3.663s] Invoked command in '/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing' returned '1': PYTEST_ADDOPTS=--tb=short --junit-xml=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml --junit-prefix=my_testing -o cache_dir=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache PYTHONDONTWRITEBYTECODE=1 /usr/bin/python3 -m pytest
