[0.139s] Invoking command in '/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing': PYTEST_ADDOPTS=--tb=short --junit-xml=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml --junit-prefix=my_testing -o cache_dir=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache -s PYTHONDONTWRITEBYTECODE=1 /usr/bin/python3 -m pytest
[0.275s] [1m============================= test session starts ==============================[0m
[0.276s] platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
[0.277s] cachedir: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache
[0.277s] rootdir: /home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing
[0.278s] plugins: launch-testing-1.0.10, ament-lint-0.12.14, ament-copyright-0.12.14, ament-xmllint-0.12.14, launch-testing-ros-0.19.10, ament-pep257-0.12.14, ament-flake8-0.12.14, colcon-core-0.19.0, cov-3.0.0
[0.340s] [1mcollecting ... [0m[1m
[0.340s] collected 1 item                                                               [0m
[0.340s] 
[0.348s] test/test_integration.py [INFO] [launch]: All log files can be found below /home/phr/.ros/log/2025-08-05-22-43-27-416244-PHR-54230
[0.348s] [INFO] [launch]: Default logging verbosity is set to INFO
[0.358s] [INFO] [number_publisher-1]: process started with pid [54244]
[0.358s] [INFO] [number_processor-2]: process started with pid [54246]
[0.383s] test_communication_and_logic (test_integration.TestIntegration) ... [0m[INFO] [1754405007.458808819] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[0.457s] [number_publisher-1] [INFO] [1754405007.532132819] [number_publisher]: 数字发布节点已启动，将从1开始发布...
[0.457s] [number_processor-2] [INFO] [1754405007.532475954] [number_processor]: 数字处理节点已启动，等待接收数字...
[1.452s] [number_publisher-1] [INFO] [1754405008.527321267] [number_publisher]: 发布: 1
[1.452s] [number_processor-2] [INFO] [1754405008.527631157] [number_processor]: 收到: 1
[1.454s] [number_processor-2] [INFO] [1754405008.528304366] [number_processor]: 发布处理后结果: 3
[2.452s] [number_publisher-1] [INFO] [1754405009.527304111] [number_publisher]: 发布: 2
[2.453s] [number_processor-2] [INFO] [1754405009.527579569] [number_processor]: 收到: 2
[2.453s] [number_processor-2] [INFO] [1754405009.528149481] [number_processor]: 发布处理后结果: 6
[3.452s] [number_publisher-1] [INFO] [1754405010.527031689] [number_publisher]: 发布: 3
[3.452s] [number_processor-2] [INFO] [1754405010.527184853] [number_processor]: 收到: 3
[3.452s] [number_processor-2] [INFO] [1754405010.527482870] [number_processor]: 发布处理后结果: 9
[3.453s] [0m[INFO] [1754405010.528378108] [test_subscriber_node]: 检查接收到的消息。 Got: [3, 6, 9][0m
[3.458s] [0m[INFO] [1754405010.531279912] [test_subscriber_node]: 测试结束，销毁测试节点[0m
[3.458s] FAIL
[3.462s] test_processor_starts_ok (test_integration.TestIntegration) ... [0m[INFO] [1754405010.537540640] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[3.462s] [0m[INFO] [1754405010.537789976] [test_subscriber_node]: 正在检查 processor 节点的启动日志...[0m
[4.452s] [number_publisher-1] [INFO] [1754405011.527038294] [number_publisher]: 发布: 4
[4.452s] [number_processor-2] [INFO] [1754405011.527138029] [number_processor]: 收到: 4
[4.452s] [number_processor-2] [INFO] [1754405011.527363620] [number_processor]: 发布处理后结果: 12
[5.452s] [number_publisher-1] [INFO] [1754405012.527320365] [number_publisher]: 发布: 5
[5.452s] [number_processor-2] [INFO] [1754405012.527656376] [number_processor]: 收到: 5
[5.453s] [number_processor-2] [INFO] [1754405012.528208479] [number_processor]: 发布处理后结果: 15
[6.452s] [number_publisher-1] [INFO] [1754405013.527023032] [number_publisher]: 发布: 6
[6.452s] [number_processor-2] [INFO] [1754405013.527309175] [number_processor]: 收到: 6
[6.452s] [number_processor-2] [INFO] [1754405013.527651123] [number_processor]: 发布处理后结果: 18
[6.464s] [0m[INFO] [1754405013.540172577] [test_subscriber_node]: 测试结束，销毁测试节点[0m
[6.465s] FAIL
[6.469s] test_publisher_starts_ok (test_integration.TestIntegration) ... [0m[INFO] [1754405013.544470668] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[6.469s] [0m[INFO] [1754405013.544693884] [test_subscriber_node]: 正在检查 publisher 节点的启动日志...[0m
[7.452s] [number_publisher-1] [INFO] [1754405014.527296806] [number_publisher]: 发布: 7
[7.452s] [number_processor-2] [INFO] [1754405014.527618569] [number_processor]: 收到: 7
[7.453s] [number_processor-2] [INFO] [1754405014.528176608] [number_processor]: 发布处理后结果: 21
[8.453s] [number_publisher-1] [INFO] [1754405015.527305815] [number_publisher]: 发布: 8
[8.453s] [number_processor-2] [INFO] [1754405015.527610956] [number_processor]: 收到: 8
[8.453s] [number_processor-2] [INFO] [1754405015.528375589] [number_processor]: 发布处理后结果: 24
[9.452s] [number_publisher-1] [INFO] [1754405016.527330267] [number_publisher]: 发布: 9
[9.453s] [number_processor-2] [INFO] [1754405016.527605725] [number_processor]: 收到: 9
[9.453s] [number_processor-2] [INFO] [1754405016.528257562] [number_processor]: 发布处理后结果: 27
[9.473s] [0m[INFO] [1754405016.548793413] [test_subscriber_node]: 测试结束，销毁测试节点[0m
[9.473s] FAIL
[9.474s] 
[9.474s] ======================================================================
[9.474s] FAIL: test_communication_and_logic (test_integration.TestIntegration)
[9.474s] ----------------------------------------------------------------------
[9.474s] Traceback (most recent call last):
[9.474s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 84, in test_communication_and_logic
[9.474s]     self.assertEqual(sorted(self.received_messages), sorted(expected_results))
[9.474s] AssertionError: Lists differ: [3, 6, 9] != [2, 4, 6]
[9.475s] 
[9.475s] First differing element 0:
[9.475s] 3
[9.475s] 2
[9.475s] 
[9.475s] - [3, 6, 9]
[9.475s] + [2, 4, 6]
[9.475s] 
[9.475s] ======================================================================
[9.475s] FAIL: test_processor_starts_ok (test_integration.TestIntegration)
[9.475s] ----------------------------------------------------------------------
[9.476s] Traceback (most recent call last):
[9.476s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 65, in test_processor_starts_ok
[9.476s]     proc_output.assertWaitFor('数字处理节点已启动，等待接收数字...',process='number_processor',stream='stdout',timeout=3)
[9.476s]   File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing/io_handler.py", line 146, in assertWaitFor
[9.476s]     assert success, 'Waiting for output timed out'
[9.476s] AssertionError: Waiting for output timed out
[9.476s] 
[9.476s] ======================================================================
[9.476s] FAIL: test_publisher_starts_ok (test_integration.TestIntegration)
[9.476s] ----------------------------------------------------------------------
[9.477s] Traceback (most recent call last):
[9.477s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 59, in test_publisher_starts_ok
[9.477s]     proc_output.assertWaitFor('数字发布节点已启动，将从1开始发布...',process='number_publisher',stream='stdout',timeout=3)
[9.477s]   File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing/io_handler.py", line 146, in assertWaitFor
[9.477s]     assert success, 'Waiting for output timed out'
[9.477s] AssertionError: Waiting for output timed out
[9.477s] 
[9.477s] ----------------------------------------------------------------------
[9.477s] Ran 3 tests in 9.124s
[9.478s] 
[9.478s] FAILED (failures=3)
[9.478s] [INFO] [number_processor-2]: sending signal 'SIGINT' to process[number_processor-2]
[9.478s] [INFO] [number_publisher-1]: sending signal 'SIGINT' to process[number_publisher-1]
[9.478s] [number_processor-2] Traceback (most recent call last):
[9.478s] [number_processor-2]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor", line 33, in <module>
[9.478s] [number_processor-2]     sys.exit(load_entry_point('my-algorithms==0.0.0', 'console_scripts', 'number_processor')())
[9.478s] [number_processor-2]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/python3.10/site-packages/my_algorithms/number_processor_node.py", line 32, in main
[9.478s] [number_processor-2]     rclpy.spin(node)
[9.479s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 229, in spin
[9.479s] [number_processor-2]     executor.spin_once()
[9.479s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
[9.479s] [number_publisher-1] Traceback (most recent call last):
[9.479s] [number_publisher-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_publisher", line 33, in <module>
[9.479s] [number_publisher-1]     sys.exit(load_entry_point('my-algorithms==0.0.0', 'console_scripts', 'number_publisher')())
[9.479s] [number_publisher-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/python3.10/site-packages/my_algorithms/number_publisher_node.py", line 25, in main
[9.479s] [number_publisher-1]     rclpy.spin(node)
[9.480s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 229, in spin
[9.480s] [number_publisher-1]     executor.spin_once()
[9.480s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
[9.480s] [number_processor-2]     self._spin_once_impl(timeout_sec)
[9.480s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
[9.480s] [number_processor-2]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[9.480s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[9.480s] [number_processor-2]     return next(self._cb_iter)
[9.480s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
[9.480s] [number_processor-2]     wait_set.wait(timeout_nsec)
[9.480s] [number_processor-2] KeyboardInterrupt
[9.480s] [number_publisher-1]     self._spin_once_impl(timeout_sec)
[9.480s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
[9.480s] [number_publisher-1]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[9.481s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[9.481s] [number_publisher-1]     return next(self._cb_iter)
[9.481s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
[9.481s] [number_publisher-1]     wait_set.wait(timeout_nsec)
[9.481s] [number_publisher-1] KeyboardInterrupt
[9.504s] [ERROR] [number_publisher-1]: process has died [pid 54244, exit code -2, cmd '/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_publisher --ros-args -r __node:=number_publisher'].
[9.505s] [ERROR] [number_processor-2]: process has died [pid 54246, exit code -2, cmd '/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor --ros-args -r __node:=number_processor'].
[9.505s] 
[9.505s] ----------------------------------------------------------------------
[9.505s] Ran 0 tests in 0.000s
[9.505s] 
[9.506s] OK
[9.515s] [31mF[0m
[9.515s] 
[9.515s] =================================== FAILURES ===================================
[9.515s] [31m[1m________________________ launch tests: test_integration ________________________[0m
[9.515s] 
[9.515s] ==========================================================================================================================================
[9.516s] FAIL: test_integration.TestIntegration.test_communication_and_logic
[9.516s] ------------------------------------------------------------------------------------------------------------------------------------------
[9.516s] Traceback (most recent call last):
[9.516s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 84, in test_communication_and_logic
[9.516s]     self.assertEqual(sorted(self.received_messages), sorted(expected_results))
[9.516s] AssertionError: Lists differ: [3, 6, 9] != [2, 4, 6]
[9.516s] 
[9.516s] First differing element 0:
[9.516s] 3
[9.516s] 2
[9.516s] 
[9.516s] - [3, 6, 9]
[9.516s] + [2, 4, 6]
[9.516s] 
[9.517s] 
[9.517s] ==========================================================================================================================================
[9.517s] FAIL: test_integration.TestIntegration.test_processor_starts_ok
[9.517s] ------------------------------------------------------------------------------------------------------------------------------------------
[9.517s] Traceback (most recent call last):
[9.517s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 65, in test_processor_starts_ok
[9.517s]     proc_output.assertWaitFor('数字处理节点已启动，等待接收数字...',process='number_processor',stream='stdout',timeout=3)
[9.517s]   File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing/io_handler.py", line 146, in assertWaitFor
[9.517s]     assert success, 'Waiting for output timed out'
[9.517s] AssertionError: Waiting for output timed out
[9.517s] 
[9.517s] 
[9.517s] ==========================================================================================================================================
[9.518s] FAIL: test_integration.TestIntegration.test_publisher_starts_ok
[9.518s] ------------------------------------------------------------------------------------------------------------------------------------------
[9.518s] Traceback (most recent call last):
[9.518s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 59, in test_publisher_starts_ok
[9.518s]     proc_output.assertWaitFor('数字发布节点已启动，将从1开始发布...',process='number_publisher',stream='stdout',timeout=3)
[9.518s]   File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing/io_handler.py", line 146, in assertWaitFor
[9.518s]     assert success, 'Waiting for output timed out'
[9.518s] AssertionError: Waiting for output timed out
[9.518s] - generated xml file: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml -
[9.518s] =========================== short test summary info ============================
[9.518s] FAILED test/test_integration.py::test_integration - test_integration.TestInte...
[9.518s] [31m============================== [31m[1m1 failed[0m[31m in 9.24s[0m[31m ===============================[0m
[9.681s] Invoked command in '/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing' returned '1': PYTEST_ADDOPTS=--tb=short --junit-xml=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml --junit-prefix=my_testing -o cache_dir=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache -s PYTHONDONTWRITEBYTECODE=1 /usr/bin/python3 -m pytest
